### ISSUE TITLE
Create a sign-up page.

### ISSUE THREAD

**Issue by asynts** [codidact/authentication#3]
There should be a 'register' or 'signup' page that can be used to create new users.

At the same time the placeholder code in `src/WebApp/Startup.cs` should be removed, it looks something like the following:

~~~csharp
using (var scope = app.ApplicationServices.CreateScope())
{
    var users = scope.ServiceProvider.GetService<UserManager<ApplicationUser>>();

    users.CreateAsync(new ApplicationUser
    {
        UserName = "admin@codidact",
        Email = "admin@codidact"
    }, "password");
}
~~~

https://github.com/codidact/authentication/pull/2#discussion_r382913717

**Comment by misha130** [comment]
@luap42 should we make a dummy page that basically works and you'll run over it later with design?

**Comment by luap42** [comment]
@misha130 Sure, go on. There are some sketch drafts from @mattjbrent, which you should look at. Otherwise, if you need help with Co-Design I'll be there. Try to minimize custom CSS for now and if you do, write a new component (like `.signup-form`). That's how I would do it.

If you want to see my ideas for a Co-Design implementation, look at https://luap42.github.io/codidact-design-draft/register.html

It'll be reviewed and refined anyways.

**Comment by asynts** [comment]
Do not go overboard with this, make it functional, not fancy. I was thinking of something like the current login page:

https://github.com/codidact/authentication/blob/master/src/WebApp/Pages/Account/Login.cshtml

**Comment by misha130** [comment]
Yes, I know. That was basically my plan too

**Comment by misha130** [comment]
What is the flow here supposed to be?

1. You go to home page of core project
2. You click on the sign up button instead of sign in
3. It moves you to the authentication instance with a form
4. You fill in the form with all your details
5. It returns you back to your homepage again?

Is there an email sent for confirmation?
Is there some sort of message that you have successfully registered which after you can return back to the home page?
Is there any documentation about this where this flow is detailed?
Pinging @cellio for some insight

**Comment by misha130** [comment]
Also there is a global display name for all the communities together?

**Comment by asynts** [comment]
In the end we will have to do some sort of email confirmation and a successful registration has to be displayed somehow, but that should be done months from now.

**Comment by misha130** [comment]
Sure that part I understand.
Plus for the emails need like an infrastructure that sends emails and stuff maybe even go for a micro service for that.

By the way as far as I can see it the register has to go API itself to the core project and tell it to create a member entity with a specific display name because the display name isn't really part of the auth

**Comment by cellio** [comment]
Oh, I didn't notice we were missing a use case for signup (we have login).  Actually there need to be two: totally new user, and user with a network account creating an account on a new site.  I'll write those after Shabbat.

For the totally new account, I think the key points would be (tell me if any of this sounds off):

- user clicks a "sign up" control
- user is presented with a form, which might be an "in-page" thing (looks like a popup) or might be a new page -- ask the design lead if it matters
- user provides display name, email address 
- check email address for uniqueness 
    - if network account exists with that email address, other use case kicks in here (need to prompt for login and then create site account and associate)
    - if unique, proceed
- prompt for password & confirmation, check that they match
- create account, assign userid (number, can't change), create associated network account

We want to do email validation but I don't know if that's MVP.  Don't let that block progress now; email requires more infrastructure and stuff, so feel free to punt for now.

Display name is purely informational.  Nothing should depend on it and it's not required to be unique.  The userid is the unique part (and the email address, which we'll never display).

Correct me if I'm wrong, but I think people log in with an email address and password, which are stored by the auth service not by the individual site -- so you go to unicorns.codidact.com and sign in, but the stuff you type there passes through to the auth service that signs you in, right?

**Comment by misha130** [comment]
> Display name is purely informational. Nothing should depend on it and it's not required to be unique. The userid is the unique part (and the email address, which we'll never display).

It is per community and not per network user, right?

> Correct me if I'm wrong, but I think people log in with an email address and password, which are stored by the auth service not by the individual site -- so you go to unicorns.codidact.com and sign in, but the stuff you type there passes through to the auth service that signs you in, right?

Sure. 

What happens actually after you sign up?
It logins automatically? You get back to the home page logged in?
It moves you to login page?

**Comment by cellio** [comment]
I think we talked about storing on the network account and allowing per-site override.  If we store the name at the network then accounts on new sites become easier.

After you sign up you should be logged in and sent back to the page where you clicked that "join" button, so back to whatever page on the site you were on originally.  Can we have some way to communicate the result (new account created, in this case) from the auth service back to the Codidact server?  That would allow the option (later) to display some contextual guidance -- welcome, here's some help, etc.  (I'm thinking of in-page notices, not sending the user to a whole new page.)  I'm not clear where the lines between front end, back end, and auth service fall for this kind of communication; I'm imagining the back end calls the auth service and thus can get some sort of response code?

**Comment by misha130** [comment]
> Can we have some way to communicate the result (new account created, in this case) from the auth service back to the Codidact server?

Basically it needs an API to connect to the Core Codidact upon the end of the registration to create a new network member and a community member. This needs to be done as part of the registration because otherwise we can't confirm that the registration has been completed successfully.  So yea that's a pretty big component that needs to be made for their inner communications.
This is done because the auth has no access to the core DB and vice versa.

So obviously for your second question it could be a flag on the member upon completion or something of the sort.

**Comment by cellio** [comment]
The flow is from the core server to the auth server and then back again, right?  That is, core is happily serving requests from the front end, and it gets one for "sign up", at which point it says "hey, auth server, do this" and waits for a response, right?  So that response can include "success" or "failure"?

Caveat: I have only a high-level understanding of this part of our architecture.  I'm trying to confirm my understanding, not make assertions.

**Comment by misha130** [comment]
Here is a flow chart where I tried to explain this

![image](https://user-images.githubusercontent.com/6649900/77204369-fa167280-6ac8-11ea-895a-8b164654df2f.png)

(There is a connection from the core frontend to the core backend to get the url for the auth frontend but I omitted to not create a confusion)

**Comment by cellio** [comment]
Oh, I see!  I thought the core frontend talked to the core backend, which talked to auth, hence my confusion.  Should I assume the the core frontend is providing the auth frontend a hunk of real estate in which to do its thing?  Because otherwise the auth stuff needs to know about things like site design, top bar, etc, and I don't think we want that.  If the core frontend tells the auth frontend "here's a 600x600px space (or whatever); do your thing", this works.

**Comment by misha130** [comment]
> Should I assume the the core frontend is providing the auth frontend a hunk of real estate in which to do its thing?

So far the plan is to move completely to a different page. Not a page within a page. A page with its own top bar that has similar design

**Comment by cellio** [comment]
Oh ok.  Sorry for the confusion that my misunderstanding caused.

**Comment by misha130** [comment]
> Oh ok. Sorry for the confusion that my misunderstanding caused.

Well, thing is whatever you say - goes. 
If you say you want an iframe inside the core instead of moving thats ok, we can discuss, see whats up and rethink it.

**Comment by luap42** [comment]
Given that auth will be community-independet AFAIK, I think we should choose the original option (page styled a little bit differently). We could either have no header, or an community-unspecific like this one:

![Draft 1: gray background, white header with shadow and auth buttons](https://user-images.githubusercontent.com/21335202/77238285-20bed100-6bcf-11ea-9d3e-c7d3b0223c3f.png)

Other ideas I had:

![Draft 1: gray background, transparent header with auth buttons](https://user-images.githubusercontent.com/21335202/77238337-654a6c80-6bcf-11ea-86e8-417caf68ee28.png)
![Draft 1: gray background, transparent header](https://user-images.githubusercontent.com/21335202/77238365-8f9c2a00-6bcf-11ea-8f2d-dc76345b4257.png)
![Draft 1: background with gradient from landing page, transparent header with auth buttons](https://user-images.githubusercontent.com/21335202/77238421-05a09100-6bd0-11ea-9425-262077febd6f.png)
![Draft 1: background with gradient from landing page, transparent header](https://user-images.githubusercontent.com/21335202/77238400-d5f18900-6bcf-11ea-8c4b-eeaa65549a23.png)

**Comment by cellio** [comment]
@luap42 that looks fine to me, and aligns with the mockup that @mattjbrent did already.  (And we did have a use case for signup; I just managed to overlook it yesterday.)  https://github.com/codidact/feature-development/tree/master/scoped/sign-up

@misha130 turns out we never actually specified the context of that dialogue (what page it's on).  From my misunderstanding of the architecture there was an "obvious" answer that doesn't make sense in the context of the actual architecture, and that's fine.  I'm not trying to assert a position, just make sure we all understand what we're doing.  This proposal is fine with me, so long as at the end of the account-creation process the user gets sent back to the original page (where the user clicked the "sign up" button).  I defer to Matt on design details.
