### ISSUE TITLE
Decide which user information is stored on the authentication server.

### ISSUE THREAD

**Issue by asynts** [codidact/authentication#8]
I think we should ask ourselves the question, what information to store on the authentication server.

Personally, we should do the following:

 1. Remove all fields from the [member entity][1] (core).

 2. When we implement something, the profile for example, we decide if we want to

     1. store that information in Authentication,

     2. store that information in Core with a default in Authentication, or

     3. store that information in Core only.

  [1]: https://github.com/codidact/core/blob/c1e82e109b8ef0ea67cf94f3a04471660d186878/src/Domain/Entities/Member.cs
  [2]: https://github.com/asynts/codidact-authentication/blob/df12fef64e000d5794480ebecb42e0124cb85390/src/Domain/Entities/ApplicationUser.cs

**Comment by misha130** [comment]
I remember discussing this with @ranolfi on discord and we came to the agreement that the Member is the profile and it should be kept as is. It should contain the profile information and should be related to the Core/Communities.

The auth user though should be completely independent and only be used for the sake of authentication so Email, Phone, et cetera things that might be used to do PII.
 (Sadly I can't link the convo but its in the backend comm somewhere)

Unlike the User, the member is the profile that you mention in point 2 that is only known to the Core app and never to the auth. 

So I'd rather keep things as is because they were sort of planned so.
